version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d 
      - ./datadir:/data/db 
      
  backend:
    image: library-backend:latest
    container_name: library-backend
    build:
      context: ./express-backend
      dockerfile: Dockerfile
    environment:
      - DB_URI=mongodb://mongodb:27017
      - COLLECTION=library
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET=2024-01-02-14:14
    depends_on:
      - mongodb

  front:
    image: libray-ui:latest
    container_name: libray-ui
    build:
      context: ./libray-ui
      dockerfile: Dockerfile
    ports:
      - "30080:80"
    depends_on:
      - backend
      - mongodb
