# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          rm -rf ../build/.git
          tar -cvf deploy.tar ../build/
          cp ./scripts/run.sh ./

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "deploy.tar, run.sh"
          target: "library"

      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            echo "start build"
            cd library
            bash run.sh
     
